default:
    image:
        name: quay.io/fenicsproject/stable:current
        entrypoint: [""]

    before_script:
        - python3 -V
        - pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

stages:
    - style
    - test

flake8:
    stage: style
    script:
        - pip install flake8
        - flake8 --config .flake8 --count --show-source --statistics .

pytest:
    stage: test
    script:
        - pip install -U .[dev]
        - pytest --cov=./
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
