name: Publish Docker Releases
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
on:
  push:
    branches: 
      - master
  release:
    types:
       - created

jobs:
  build-layout-generator:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Publish Master to Docker
        # publish master
        uses: docker/build-push-action@v1.1.0
        if: github.event_name == 'push'
        with:
          repository: zweien/layout-generator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockers/Dockerfile
          tags: latest
        timeout-minutes: 40